# Generated by Django 5.1.7 on 2025-03-29 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_team_college'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants1', to='management.college'),
        ),
    ]
